services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: causa-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - WATCHFILES_FORCE_POLLING=true # Often needed for hot reload in Docker on some systems
