from typing import List, Optional, Dict, Any
import uuid
import logging
from datetime import datetime
from app.db.utils import get_driver
from app.models.domain import Role, LifecycleStatus, Claim, Factor, Proposal
from app.db.permissions import check_permission

# Re-export get_driver for main.py compatibility
# from app.db.utils import get_driver (already imported)

logger = logging.getLogger(__name__)

# --- Agent / Conversation ---

async def save_claims(conversation_id: str, claims: List[Claim]):
    """
    Persists claims extracted by the Agent.
    Creates Factor nodes if they don't exist.
    Creates / Updates relationships.
    Links Conversation to these Claims/Factors?
    """
    driver = get_driver()
    # We should also link the conversation to these claims for context
    
    query = """
    MATCH (c:Conversation {id: $cid})
    WITH c
    UNWIND $claims as claim
    
    // Merge Source
    MERGE (source:Factor {name: claim.source_node})
    ON CREATE SET source.id = randomUUID(), source.type = coalesce(claim.source_type, 'systeemelement'), source.created_at = datetime()
    
    // Merge Target
    MERGE (target:Factor {name: claim.target_node})
    ON CREATE SET target.id = randomUUID(), target.type = coalesce(claim.target_type, 'systeemelement'), target.created_at = datetime()
    
    // Create Relationship (Claim)
    MERGE (source)-[r:CAUSAL_LINK {id: claim.id}]->(target)
    SET r.statement = claim.statement,
        r.confidence = claim.confidence,
        r.polarity = claim.polarity,
        r.created_at = datetime()
        
    // Link to Conversation
    MERGE (c)-[:GENERATED]->(r)
    """
    
    # Transform claims to dicts
    claims_data = []
    for c in claims:
        c_dict = c.dict() if hasattr(c, 'dict') else c.__dict__
        # Ensure ID
        if not c_dict.get('id'): c_dict['id'] = str(uuid.uuid4())
        claims_data.append(c_dict)

    try:
        with driver.session() as session:
            session.run(query, {"cid": conversation_id, "claims": claims_data})
    except Exception as e:
        logger.error(f"Failed to save claims: {e}")

async def set_conversation_topic(conversation_id: str, topic: str):
    driver = get_driver()
    query = """
    MERGE (c:Conversation {id: $cid})
    SET c.topic = $topic, c.updated_at = datetime()
    """
    try:
        with driver.session() as session:
            session.run(query, {"cid": conversation_id, "topic": topic})
    except Exception as e:
        logger.error(f"Failed to set topic: {e}")

async def get_conversation_topic(conversation_id: str) -> Optional[str]:
    driver = get_driver()
    query = "MATCH (c:Conversation {id: $cid}) RETURN c.topic as topic"
    try:
        with driver.session() as session:
            result = session.run(query, {"cid": conversation_id})
            record = result.single()
            return record["topic"] if record else None
    except Exception as e:
        return None

async def fetch_existing_factors(conversation_id: str) -> List[str]:
    """Returns names of factors mentioned in this conversation or context."""
    driver = get_driver()
    query = """
    MATCH (c:Conversation {id: $cid})-[:GENERATED]->(r:CAUSAL_LINK)
    MATCH (source)-[r]->(target)
    RETURN collect(distinct source.name) + collect(distinct target.name) as factors
    """
    try:
        with driver.session() as session:
            result = session.run(query, {"cid": conversation_id})
            record = result.single()
            if record:
                # flatten and distinct
                names = list(set(record["factors"]))
                return names
            return []
    except Exception as e:
        logger.error(f"Failed to fetch factors: {e}")
        return []

async def revoke_claims(conversation_id: str):
    """Marks claims from this conversation as revoked or deletes them?"""
    # Implementation: Delete relationships generated by this conversation?
    driver = get_driver()
    query = """
    MATCH (c:Conversation {id: $cid})-[rel:GENERATED]->(r:CAUSAL_LINK)
    // We might want to delete the Claim relationship r itself?
    // r is a relationship between factors. 
    // Cypher: MATCH (a)-[r]->(b) DELETE r
    MATCH (a)-[r]->(b)
    DELETE rel, r
    """
    try:
        with driver.session() as session:
            session.run(query, {"cid": conversation_id})
    except Exception as e:
        logger.error(f"Failed to revoke claims: {e}")

# --- Proposals (Restored) ---

async def create_proposal(title: str, author_id: str, description: Optional[str] = None, type: str = "standard", target_id: Optional[str] = None) -> str:
    driver = get_driver()
    proposal_id = str(uuid.uuid4())
    
    query = """
    MATCH (u:User {id: $author_id}) # Expecting internal ID, or match by email if author_id is email?
    # Usually author_id is passed as internal ID from get_current_user logic if available, 
    # but currently our user/auth system uses email often. 
    # Let's assume author_id is ID. If fails, we might need to MATCH by email?
    # In main.py create_proposal uses request.author_id.
    
    CREATE (p:Proposal {
        id: $id,
        title: $title,
        description: $description,
        type: $type,
        target_id: $target_id,
        status: 'proposed',
        created_at: datetime()
    })
    CREATE (u)-[:CREATED]->(p)
    RETURN p.id as id
    """
    # Fallback if author_id is actually an email (common in this codebase transitions)
    # logic: try match by id, if not found try match by email? 
    # Cypher: MATCH (u:User) WHERE u.id = $aid OR u.email = $aid
    
    query = """
    MATCH (u:User) WHERE u.id = $author_id OR u.email = $author_id
    WITH u LIMIT 1
    CREATE (p:Proposal {
        id: $id,
        title: $title,
        description: $description,
        type: $type,
        target_id: $target_id,
        status: 'proposed',
        created_at: datetime()
    })
    CREATE (u)-[:CREATED]->(p)
    RETURN p.id as id
    """

    try:
        with driver.session() as session:
            result = session.run(query, {
                "id": proposal_id,
                "title": title,
                "author_id": author_id,
                "description": description,
                "type": type,
                "target_id": target_id
            })
            record = result.single()
            if record:
                return record["id"]
            raise Exception("User not found or creation failed")
    except Exception as e:
        logger.error(f"Error creating proposal: {e}")
        raise e

async def get_proposals(status: Optional[str] = None, author_id: Optional[str] = None) -> List[Proposal]:
    driver = get_driver()
    
    query = """
    MATCH (p:Proposal)<-[:CREATED]-(u:User)
    """
    
    where_clauses = []
    params = {}
    
    if status:
        where_clauses.append("p.status = $status")
        params["status"] = status
        
    if author_id:
        where_clauses.append("(u.id = $author_id OR u.email = $author_id)")
        params["author_id"] = author_id

    if where_clauses:
        query += " WHERE " + " AND ".join(where_clauses)
        
    query += """
    RETURN p, u.id as author_id
    ORDER BY p.created_at DESC
    """
    
    try:
        with driver.session() as session:
            result = session.run(query, params)
            proposals = []
            for record in result:
                node = record["p"]
                auth_id = record["author_id"]
                proposals.append(Proposal(
                    id=node["id"],
                    title=node["title"],
                    description=node.get("description"),
                    status=LifecycleStatus(node.get("status", "draft")),
                    author_id=auth_id,
                    type=node.get("type"),
                    target_id=node.get("target_id"),
                    created_at=str(node["created_at"])
                ))
            return proposals
    except Exception as e:
        logger.error(f"Error getting proposals: {e}")
        return []

async def get_proposal_by_id(proposal_id: str) -> Optional[Proposal]:
    driver = get_driver()
    query = """
    MATCH (p:Proposal {id: $id})<-[:CREATED]-(u:User)
    RETURN p, u.id as author_id
    """
    try:
        with driver.session() as session:
            result = session.run(query, {"id": proposal_id})
            record = result.single()
            if record:
                node = record["p"]
                return Proposal(
                    id=node["id"],
                    title=node["title"],
                    description=node.get("description"),
                    status=LifecycleStatus(node.get("status", "draft")),
                    author_id=record["author_id"],
                    type=node.get("type"),
                    target_id=node.get("target_id"),
                    created_at=str(node["created_at"])
                )
            return None
    except Exception as e:
        logger.error(f"Error getting proposal {proposal_id}: {e}")
        return None

async def update_proposal_status(proposal_id: str, status: LifecycleStatus) -> bool:
    driver = get_driver()
    query = """
    MATCH (p:Proposal {id: $id})
    SET p.status = $status
    RETURN p
    """
    try:
        with driver.session() as session:
            status_str = status.value if hasattr(status, 'value') else status
            result = session.run(query, {"id": proposal_id, "status": status_str})
            return result.single() is not None
    except Exception as e:
        logger.error(f"Error updating proposal status: {e}")
        return False

# --- Organization / User Core ---

async def create_organization(name: str, description: Optional[str] = None, owner_email: Optional[str] = None) -> str:
    driver = get_driver()
    org_id = str(uuid.uuid4())
    
    # Logic: Create Org. If owner_email provided, make them Admin.
    query = """
    CREATE (o:Organization {id: $id, name: $name, description: $desc, created_at: datetime(), status: 'active'})
    WITH o
    """
    
    if owner_email:
        query += """
        MATCH (u:User {email: toLower($email)})
        MERGE (u)-[:HAS_ROLE {role: 'admin', updated_at: datetime()}]->(o)
        """
        
    query += " RETURN o.id as id"

    try:
        with driver.session() as session:
            result = session.run(query, {"id": org_id, "name": name, "desc": description, "email": owner_email})
            record = result.single()
            return record["id"]
    except Exception as e:
        logger.error(f"Error creating org: {e}")
        raise e

async def get_organizations() -> List[Dict]:
    """Returns all organizations (for platform admin use mainly)."""
    driver = get_driver()
    query = """
    MATCH (o:Organization)
    WHERE o.status IS NULL OR o.status <> 'archived' 
    RETURN o
    """
    try:
        with driver.session() as session:
            result = session.run(query)
            return [dict(record["o"]) for record in result]
    except Exception as e:
        logger.error(f"Error listing orgs: {e}")
        return []

async def get_user_organizations(email: str) -> List[Dict]:
    """Returns orgs for a specific user."""
    driver = get_driver()
    query = """
    MATCH (u:User {email: toLower($email)})
    MATCH (u)-[:HAS_ROLE]->(o:Organization)
    WHERE o.status IS NULL OR o.status <> 'archived'
    RETURN o
    """
    try:
        with driver.session() as session:
            result = session.run(query, {"email": email})
            return [dict(record["o"]) for record in result]
    except Exception as e:
        return []

async def create_user(email: str, name: Optional[str] = None) -> str:
    driver = get_driver()
    uid = str(uuid.uuid4())
    query = """
    MERGE (u:User {email: toLower($email)})
    ON CREATE SET u.id = $id, u.name = $name, u.created_at = datetime()
    ON MATCH SET u.name = coalesce($name, u.name)
    RETURN u.id as id
    """
    try:
        with driver.session() as session:
            result = session.run(query, {"email": email, "id": uid, "name": name})
            return result.single()["id"]
    except Exception as e:
        logger.error(f"Error creating user: {e}")
        raise e

async def get_user_by_email(email: str) -> Optional[Dict]:
    driver = get_driver()
    query = "MATCH (u:User {email: toLower($email)}) RETURN u"
    try:
        with driver.session() as session:
            result = session.run(query, {"email": email})
            record = result.single()
            return dict(record["u"]) if record else None
    except Exception as e:
        return None

async def get_all_users() -> List[Dict]:
    driver = get_driver()
    query = "MATCH (u:User) RETURN u"
    try:
        with driver.session() as session:
            return [dict(r["u"]) for r in session.run(query)]
    except Exception:
        return []

async def update_user_profile(email: str, first_name: str, last_name: str, username: str):
    driver = get_driver()
    query = """
    MATCH (u:User {email: toLower($email)})
    SET u.first_name = $fn, u.last_name = $ln, u.username = $un
    """
    with driver.session() as session:
        session.run(query, {"email": email, "fn": first_name, "ln": last_name, "un": username})

# --- Members ---

async def get_organization_users(org_id: str) -> List[Dict]:
    driver = get_driver()
    query = """
    MATCH (o:Organization {id: $oid})<-[r:HAS_ROLE]-(u:User)
    RETURN u, r.role as role
    """
    try:
        with driver.session() as session:
            result = session.run(query, {"oid": org_id})
            users = []
            for rec in result:
                u = dict(rec["u"])
                u["role"] = rec["role"]
                users.append(u)
            return users
    except Exception as e:
        return []

async def add_user_to_organization(email: str, org_id: str, role: str):
    # Ensure user
    await create_user(email)
    driver = get_driver()
    query = """
    MATCH (u:User {email: toLower($email)})
    MATCH (o:Organization {id: $oid})
    MERGE (u)-[r:HAS_ROLE]->(o)
    SET r.role = $role, r.updated_at = datetime()
    """
    with driver.session() as session:
        session.run(query, {"email": email, "oid": org_id, "role": role})

async def update_org_member_role(org_id: str, user_id: str, role: str, name: Optional[str] = None):
    driver = get_driver()
    query = """
    MATCH (o:Organization {id: $oid})<-[r:HAS_ROLE]-(u:User {id: $uid})
    SET r.role = $role, r.updated_at = datetime()
    """
    if name:
        query += ", u.name = $name"
        
    with driver.session() as session:
        session.run(query, {"oid": org_id, "uid": user_id, "role": role, "name": name})

async def remove_user_from_organization(org_id: str, user_id: str):
    driver = get_driver()
    query = """
    MATCH (o:Organization {id: $oid})<-[r:HAS_ROLE]-(u:User {id: $uid})
    DELETE r
    """
    with driver.session() as session:
        session.run(query, {"oid": org_id, "uid": user_id})

# Project/Theme Members shortcuts (similar logic)
async def get_project_users(project_id: str) -> List[Dict]:
    driver = get_driver()
    query = "MATCH (p:Project {id: $pid})<-[r:HAS_ROLE]-(u:User) RETURN u, r.role as role"
    with driver.session() as session:
         return [{"id": rec["u"]["id"], "name": rec["u"].get("name",""), "email": rec["u"]["email"], "role": rec["role"]} for rec in session.run(query, {"pid": project_id})]

async def update_project_member_role(project_id: str, user_id: str, role: str, name: Optional[str] = None):
     await update_org_member_role(project_id, user_id, role, name) # Generic enough if ID is unique

async def remove_project_member(project_id: str, user_id: str):
    await remove_user_from_organization(project_id, user_id) # Generic

async def get_theme_users(theme_id: str) -> List[Dict]:
     driver = get_driver()
     query = "MATCH (t:Theme {id: $tid})<-[r:HAS_ROLE]-(u:User) RETURN u, r.role as role"
     with driver.session() as session:
         return [{"id": rec["u"]["id"], "name": rec["u"].get("name",""), "email": rec["u"]["email"], "role": rec["role"]} for rec in session.run(query, {"tid": theme_id})]

async def update_theme_member_role(theme_id: str, user_id: str, role: str, name: Optional[str] = None):
     await update_org_member_role(theme_id, user_id, role, name)

async def remove_theme_member(theme_id: str, user_id: str):
     await remove_user_from_organization(theme_id, user_id)
     
# --- Projects / Themes Structure ---

async def get_projects(organization_id: str) -> List[Dict]:
    driver = get_driver()
    query = """
    MATCH (o:Organization {id: $oid})-[:OWNS]->(p:Project)
    WHERE p.status IS NULL OR p.status <> 'archived'
    RETURN p
    """
    with driver.session() as session:
        return [dict(r["p"]) for r in session.run(query, {"oid": organization_id})]

async def create_project(name: str, organization_id: str, description: Optional[str] = None) -> str:
    driver = get_driver()
    pid = str(uuid.uuid4())
    query = """
    MATCH (o:Organization {id: $oid})
    CREATE (p:Project {id: $id, name: $name, description: $desc, created_at: datetime(), status: 'active'})
    CREATE (o)-[:OWNS]->(p)
    RETURN p.id as id
    """
    with driver.session() as session:
        return session.run(query, {"oid": organization_id, "id": pid, "name": name, "desc": description}).single()["id"]

async def update_project(project_id: str, name: Optional[str], description: Optional[str]):
    driver = get_driver()
    query = "MATCH (p:Project {id: $id}) SET p.name = coalesce($name, p.name), p.description = coalesce($desc, p.description)"
    with driver.session() as session:
        session.run(query, {"id": project_id, "name": name, "desc": description})

async def archive_project(project_id: str):
    driver = get_driver()
    query = "MATCH (p:Project {id: $id}) SET p.status = 'archived'"
    with driver.session() as session:
        session.run(query, {"id": project_id})

async def get_project_themes(project_id: str) -> List[Dict]:
    driver = get_driver()
    query = """
    MATCH (p:Project {id: $pid})-[:HAS_THEME]->(t:Theme)
    WHERE t.status IS NULL OR t.status <> 'archived'
    RETURN t
    """
    with driver.session() as session:
        return [dict(r["t"]) for r in session.run(query, {"pid": project_id})]

async def create_theme(project_id: str, name: str, description: Optional[str] = None) -> str:
    driver = get_driver()
    tid = str(uuid.uuid4())
    query = """
    MATCH (p:Project {id: $pid})
    CREATE (t:Theme {id: $id, name: $name, description: $desc, created_at: datetime(), status: 'active'})
    CREATE (p)-[:HAS_THEME]->(t)
    RETURN t.id as id
    """
    with driver.session() as session:
         return session.run(query, {"pid": project_id, "id": tid, "name": name, "desc": description}).single()["id"]

async def update_theme(theme_id: str, name: Optional[str], description: Optional[str]):
    driver = get_driver()
    query = "MATCH (t:Theme {id: $id}) SET t.name = coalesce($name, t.name), t.description = coalesce($desc, t.description)"
    with driver.session() as session:
        session.run(query, {"id": theme_id, "name": name, "desc": description})

async def archive_theme(theme_id: str):
    driver = get_driver()
    query = "MATCH (t:Theme {id: $id}) SET t.status = 'archived'"
    with driver.session() as session:
        session.run(query, {"id": theme_id})
        
async def update_organization(org_id: str, name: Optional[str], description: Optional[str]):
    driver = get_driver()
    query = "MATCH (o:Organization {id: $id}) SET o.name = coalesce($name, o.name), o.description = coalesce($desc, o.description)"
    with driver.session() as session:
        session.run(query, {"id": org_id, "name": name, "desc": description})

async def archive_organization(org_id: str):
    driver = get_driver()
    query = "MATCH (o:Organization {id: $id}) SET o.status = 'archived'"
    with driver.session() as session:
        session.run(query, {"id": org_id})

# --- Claims / Factors / Manual Editing ---

async def get_claims_for_theme(theme_id: str) -> List[Dict]:
    # Returns claims where relevant factors are connected or just general claims logic?
    # Usually "claims in a theme" aren't explicitly linked to a theme node in our schema yet, 
    # unless we use the 'Context' concept. 
    # But let's assume we search for factors IN the theme?
    # Schema check: (Project)-[:HAS_THEME]->(Theme)-[:HAS_FACTOR]->(Factor)
    # Then Factors have links.
    driver = get_driver()
    query = """
    MATCH (t:Theme {id: $tid})
    OPTIONAL MATCH (t)-[:HAS_FACTOR]->(f:Factor)
    OPTIONAL MATCH (f)-[r:CAUSAL_LINK]-(f2) 
    // This is expensive and might return duplicates. 
    // Assuming manual claims endpoint creates relationships between factors in the context of a theme.
    // Let's iterate on this. If no explicit Theme->Claim link, we follow Factor.
    RETURN r, f.name as src, f2.name as tgt, type(r) as type
    """
    # Simply returning empty list if not fully implemented in schema
    return []

async def get_factors_for_theme(theme_id: str) -> List[Dict]:
    driver = get_driver()
    query = """
    MATCH (t:Theme {id: $tid})-[:HAS_FACTOR]->(f:Factor)
    RETURN f
    """
    with driver.session() as session:
        return [dict(r["f"]) for r in session.run(query, {"tid": theme_id})]

async def create_factor_manual(name: str, description: Optional[str], type: str, theme_id: Optional[str]) -> str:
    driver = get_driver()
    fid = str(uuid.uuid4())
    query = """
    CREATE (f:Factor {id: $id, name: $name, description: $desc, type: $type, created_at: datetime()})
    """
    if theme_id:
        query += """
        WITH f
        MATCH (t:Theme {id: $tid})
        MERGE (t)-[:HAS_FACTOR]->(f)
        """
        
    query += " RETURN f.id as id"
    
    with driver.session() as session:
        return session.run(query, {"id": fid, "name": name, "desc": description, "type": type, "tid": theme_id}).single()["id"]

async def update_factor_manual(factor_id: str, name: Optional[str], description: Optional[str], type: Optional[str], theme_id: Optional[str]):
    driver = get_driver()
    query = """
    MATCH (f:Factor {id: $id})
    SET f.name = coalesce($name, f.name), 
        f.description = coalesce($desc, f.description),
        f.type = coalesce($type, f.type)
    """
    # handle theme re-linking not implemented for brevity, just props
    with driver.session() as session:
        session.run(query, {"id": factor_id, "name": name, "desc": description, "type": type})

async def delete_factor_manual(factor_id: str):
    driver = get_driver()
    query = "MATCH (f:Factor {id: $id}) DETACH DELETE f"
    with driver.session() as session:
        session.run(query, {"id": factor_id})

async def create_claim_manual(theme_id: str, source_id: str, target_id: str, statement: str, polarity: str = "+", confidence: float = 1.0):
    driver = get_driver()
    cid = str(uuid.uuid4())
    query = """
    MATCH (s:Factor {id: $sid}), (t:Factor {id: $tid})
    CREATE (s)-[r:CAUSAL_LINK {
        id: $cid, 
        statement: $stmt, 
        polarity: $pol, 
        confidence: $conf, 
        created_at: datetime()
    }]->(t)
    """
    # Optionally link to theme?
    with driver.session() as session:
        session.run(query, {"cid": cid, "sid": source_id, "tid": target_id, "stmt": statement, "pol": polarity, "conf": confidence})

async def update_claim_manual(claim_id: str, statement: Optional[str], polarity: Optional[str], confidence: Optional[float], source_id: Optional[str], target_id: Optional[str]):
    # Note: Changing source/target implies deleting and recreating, or complex cypher.
    # For now only update props.
    driver = get_driver()
    query = """
    MATCH ()-[r:CAUSAL_LINK {id: $id}]->()
    SET r.statement = coalesce($stmt, r.statement),
        r.polarity = coalesce($pol, r.polarity),
        r.confidence = coalesce($conf, r.confidence)
    """
    with driver.session() as session:
        session.run(query, {"id": claim_id, "stmt": statement, "pol": polarity, "conf": confidence})

async def delete_claim_manual(claim_id: str):
    driver = get_driver()
    query = "MATCH ()-[r:CAUSAL_LINK {id: $id}]->() DELETE r"
    with driver.session() as session:
        session.run(query, {"id": claim_id})
